default[:goapp][:gobin] = '/usr/local/golang/bin'
default[:goapp][:app_path] = '/app/'
default[:goapp][:app_user] = 'goapp'
default[:goapp][:app_group] = 'staff'
default[:goapp][:gitrepo] = 'https://github.com/urtens/golang.git'
